server:
  port: 8888

spring:
# 数据源连接
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    open-in-view: false
    generate-ddl: false
    hibernate:
#      使用了JPA的自动建表
      ddl-auto: update
# h2: 仅mem模式下使用；tcp模式下注释此配置；
#  h2:
#    console:
#      path: /h2-console
#      enabled: true
#      settings:
#        web-allow-others: true
  datasource:
#    url: jdbc:h2:mem:~/dev/h2/data/spring-boot-1;MODE=MySql;DB_CLOSE_DELAY=-1
    url: jdbc:h2:tcp://localhost/~/dev/h2/data/spring-boot-1
#    driver-class-name: com.mysql.jdbc.Driver
    username: sa
    password:
#    schema: classpath:sql/springboot1_readinglist-schema.sql
#    data: classpath:sql/springboot1_readinglist-data.sql

